// List the format of all security events

const SecurityEventType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  BRUTE_FORCE_DETECTED: 'BRUTE_FORCE_DETECTED',
  MFA_CHALLENGE: 'MFA_CHALLENGE',
  MFA_SUCCESS: 'MFA_SUCCESS',
  MFA_FAILURE: 'MFA_FAILURE',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  TOKEN_ISSUED: 'TOKEN_ISSUED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
};

module.exports = {
  SecurityEventType,
};
